version: '3'

services:
  app:
    image: counter:latest
    restart: on-failure
    env_file:
      - ./app.env
    ports:
      - "8083:8083"
    depends_on:
      - cache
    deploy:
      replicas: 1
  cache:
    image: redis:6.2-alpine
    restart: always
    env_file:
      - ./app.env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local